### ISSUE TITLE
java.lang.IllegalArgumentException: the bind value at index 1 is null

### ISSUE THREAD

**Issue by WangGuox1n** [evancharlton/android-mileage#69]
Hi, I developed an automatic-testing tool and it detected an exception in your app(version 3.1.1).
I would like to know if you consider it as a bug?

**STACK_TRACE**=E/AndroidRuntime( 7316): FATAL EXCEPTION: main
E/AndroidRuntime( 7316): Process: com.evancharlton.mileage, PID: 7316
E/AndroidRuntime( 7316): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.evancharlton.mileage/com.evancharlton.mileage.charts.AverageDistanceChart}: java.lang.IllegalArgumentException: the bind value at index 1 is null
E/AndroidRuntime( 7316): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
E/AndroidRuntime( 7316): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/AndroidRuntime( 7316): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 7316): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 7316): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7316): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 7316): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 7316): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 7316): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 7316): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 7316): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 7316): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 7316): **Caused by: java.lang.IllegalArgumentException: the bind value at index 1 is null**
E/AndroidRuntime( 7316): 	at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
E/AndroidRuntime( 7316): 	at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
E/AndroidRuntime( 7316): 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
E/AndroidRuntime( 7316): 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
E/AndroidRuntime( 7316): 	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
E/AndroidRuntime( 7316): 	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
E/AndroidRuntime( 7316): 	at com.evancharlton.mileage.provider.FillUpsProvider.query(FillUpsProvider.java:243)
E/AndroidRuntime( 7316): 	at android.content.ContentProvider.query(ContentProvider.java:857)
E/AndroidRuntime( 7316): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:200)
E/AndroidRuntime( 7316): 	at android.content.ContentResolver.query(ContentResolver.java:461)
E/AndroidRuntime( 7316): 	at android.content.ContentResolver.query(ContentResolver.java:404)
E/AndroidRuntime( 7316): 	at android.app.Activity.managedQuery(Activity.java:1796)
E/AndroidRuntime( 7316): 	at com.evancharlton.mileage.charts.LineChart.getVehicle(LineChart.java:44)
E/AndroidRuntime( 7316): 	at com.evancharlton.mileage.charts.DistanceChart.createChartGenerator(DistanceChart.java:9)
E/AndroidRuntime( 7316): 	at com.evancharlton.mileage.ChartActivity.restoreLastNonConfigurationInstance(ChartActivity.java:74)
E/AndroidRuntime( 7316): 	at com.evancharlton.mileage.ChartActivity.onCreate(ChartActivity.java:36)
E/AndroidRuntime( 7316): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 7316): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 7316): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/AndroidRuntime( 7316): 	... 11 more

**Comment by WangGuox1n** [comment]
Second exception:

**STACK_TRACE**=E/AndroidRuntime(28944): FATAL EXCEPTION: main
E/AndroidRuntime(28944): Process: com.evancharlton.mileage, PID: 28944
E/AndroidRuntime(28944): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.evancharlton.mileage/com.evancharlton.mileage.charts.AverageVolumeChart}: java.lang.IllegalArgumentException: Point already added to series
E/AndroidRuntime(28944): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
E/AndroidRuntime(28944): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/AndroidRuntime(28944): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3724)
E/AndroidRuntime(28944): 	at android.app.ActivityThread.access$900(ActivityThread.java:135)
E/AndroidRuntime(28944): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
E/AndroidRuntime(28944): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(28944): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(28944): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(28944): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(28944): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(28944): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(28944): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(28944): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(28944): **Caused by: java.lang.IllegalArgumentException: Point already added to series**
E/AndroidRuntime(28944): 	at com.artfulbits.aiCharts.Base.ChartPointCollection.add(Unknown Source)
E/AndroidRuntime(28944): 	at com.evancharlton.mileage.charts.LineChart.unserializeData(LineChart.java:63)
E/AndroidRuntime(28944): 	at com.evancharlton.mileage.ChartActivity.restoreLastNonConfigurationInstance(ChartActivity.java:72)
E/AndroidRuntime(28944): 	at com.evancharlton.mileage.ChartActivity.onCreate(ChartActivity.java:36)
E/AndroidRuntime(28944): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime(28944): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(28944): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/AndroidRuntime(28944): 	... 12 more
